2021-05-17 01:07:48,884 ERROR [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File ".\openclducominer.py", line 70, in reconnect
    soc.connect((pool_address, int(pool_port)))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2021-05-17 01:08:15,239 ERROR [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File ".\openclducominer.py", line 70, in reconnect
    soc.connect((pool_address, int(pool_port)))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2021-05-17 01:08:41,665 ERROR [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File ".\openclducominer.py", line 70, in reconnect
    soc.connect((pool_address, int(pool_port)))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2021-05-17 01:09:08,087 ERROR [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File ".\openclducominer.py", line 70, in reconnect
    soc.connect((pool_address, int(pool_port)))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
